### ISSUE TITLE
errors return console.origin?

### ISSUE THREAD

**Issue by kentonbmax** [kgroat/async-catcher#1]
Need the origin details of internal server errors. Currently we are not seeing node stack info and origin info. 

[console.trace](https://millermedeiros.github.io/mdoc/examples/node_api/doc/stdio.html#console.trace)

throw the sample below in tonicdev. 

require("moment");

try{
    var m = moment();
} catch(err){
    console.trace(err);
    console.log(err);
    console.error(err);
}

**Comment by kgroat** [comment]
This would be the purpose of further-down middleware, not an issue for this module.
